defaults: &defaults
  allow_dynamic_fields: true
  raise_not_found_error: true
  identity_map_enabled: true


development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: rails3_extjs
  options:
    <<: *defaults

test:
  <<: *defaults
  host: localhost
  database: test
